
CREATE USER mkaplan WITH SUPERUSER PASSWORD 'mkaplan';
ALTER SYSTEM SET max_connections = '1024';
CREATE USER mkreplication REPLICATION LOGIN CONNECTION LIMIT 100 ENCRYPTED PASSWORD 'mkreplication';

